#!/usr/bin/env bash
#Displays "BEst School" 10 times using a while loop.
#On the 9th iteation, displays "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
